- name: variables from inventory
  hosts: localhost
  vars_files:
  - vars.yaml
  vars:
    timings: "07:15 IST"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}, Timings are {{timings}}"